- include: webapp.yml

#- include: accesspoint.yml


#- include: init.yml


- name: Install Cernwall related packages
  tags: apt
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - rpi-update
  - mosquitto
  - mosquitto-clients
  - supervisor
  - nginx-full
  - i2c-tools
  - python3-smbus 
  - python-smbus
  

#  - samba 
#  - samba-common-bin

- name: Run rpi-update
  command: rpi-update
  become: true



- include: modules.yml


#- name: Checkout Raspi repository
#  git: repo=https://github.com/aapris/VekotinVerstas.git dest={{ user_home }} update=no

#- name: Download node for Raspi
#  get_url:
#    url: https://nodejs.org/dist/v6.10.3/node-v6.10.3-linux-armv6l.tar.xz
#    dest: {{ user_home }}/node-v6.10.3-linux-armv6l.tar.xz
#    mode: 0440

#- name: Unarchive downloaded node archive
#   unarchive:
#    src: {{ user_home }}/node-v6.10.3-linux-armv6l.tar.xz
#    dest: /tmp/node

#- name: Move node to /usr/local
#  shell: |
#    sudo cp -av /tmp/node/{bin,include,lib,share} /usr/local
#    rm -rf /tmp/node
#    exit 0
